---
# 3Tier App Main Playbook

- name: Common Tasks
  hosts: all
  gather_facts: false
  become: true
  roles:
   - common 

- name: Configure Frontends
  hosts: frontends
  gather_facts: false
  become: true
  roles:
   - lb-tier

- name: Configure Apps
  hosts: apps
  gather_facts: false
  become: true
  roles:
   - app-tier

- name: Configure DB
  hosts: appdbs
  gather_facts: false
  become: true
  roles:
   - db-tier 
...
