---
# tasks file for roles/db-tier
- name: Install Postgresql
  yum: 
    name: [ '{{ item }}' ]
    state: latest
  with_items:
    - "{{ postgresql_pkg }}"

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Initialize Postgresql
  command: postgresql-setup initdb

- name: Enable Postgres at boot
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - "{{ postgresql_srv }}"

